### ISSUE TITLE
[Question] Kotlin rewrite

### ISSUE THREAD

**Issue by ngortheone** [aaschmid/taskwarrior-java-client#4]
Kotlin has Java6 as compilation target and nice syntactic sugar.
All that makes it easier using it on Android.

I am willing to work on Kotlin rewrite if you are willing to accept the PR

**Comment by aaschmid** [comment]
We can of course do a rewrite in Kotlin. This should be quite easy :-)

Edit: So I will wait for your PR, otherwise I am interesting in doing it myself to refresh my Kotlin knowledge. Also I think we should maybe keep the java8 version in a separate branch.

**Comment by aaschmid** [comment]
No more progress on this issue, will close it for now. Don't hesitate to reopen :-)

Moreover, I would be interested in the use cases which are not well integrating with Kotlin because currently I want to keep the dependencies of this library as small as possible.
